/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBaseLegalRouteImport } from './routes/_authenticated/base-legal'
import { Route as AuthenticatedAtualizacoesRouteImport } from './routes/_authenticated/atualizacoes'
import { Route as AuthenticatedEmpresasIndexRouteImport } from './routes/_authenticated/empresas.index'
import { Route as AuthenticatedEmpresasEmpresaIdRouteImport } from './routes/_authenticated/empresas.$empresaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBaseLegalRoute = AuthenticatedBaseLegalRouteImport.update({
  id: '/base-legal',
  path: '/base-legal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtualizacoesRoute =
  AuthenticatedAtualizacoesRouteImport.update({
    id: '/atualizacoes',
    path: '/atualizacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresasIndexRoute =
  AuthenticatedEmpresasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)
const AuthenticatedEmpresasEmpresaIdRoute =
  AuthenticatedEmpresasEmpresaIdRouteImport.update({
    id: '/$empresaId',
    path: '/$empresaId',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/base-legal': typeof AuthenticatedBaseLegalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
  '/empresas/': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/base-legal': typeof AuthenticatedBaseLegalRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
  '/empresas': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/_authenticated/base-legal': typeof AuthenticatedBaseLegalRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
  '/_authenticated/empresas/': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/atualizacoes'
    | '/base-legal'
    | '/dashboard'
    | '/empresas'
    | '/simulador'
    | '/usuarios'
    | '/empresas/$empresaId'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atualizacoes'
    | '/base-legal'
    | '/dashboard'
    | '/simulador'
    | '/usuarios'
    | '/empresas/$empresaId'
    | '/empresas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/atualizacoes'
    | '/_authenticated/base-legal'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/simulador'
    | '/_authenticated/usuarios'
    | '/_authenticated/empresas/$empresaId'
    | '/_authenticated/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/base-legal': {
      id: '/_authenticated/base-legal'
      path: '/base-legal'
      fullPath: '/base-legal'
      preLoaderRoute: typeof AuthenticatedBaseLegalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atualizacoes': {
      id: '/_authenticated/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AuthenticatedAtualizacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas/': {
      id: '/_authenticated/empresas/'
      path: '/'
      fullPath: '/empresas/'
      preLoaderRoute: typeof AuthenticatedEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
    '/_authenticated/empresas/$empresaId': {
      id: '/_authenticated/empresas/$empresaId'
      path: '/$empresaId'
      fullPath: '/empresas/$empresaId'
      preLoaderRoute: typeof AuthenticatedEmpresasEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
  }
}

interface AuthenticatedEmpresasRouteChildren {
  AuthenticatedEmpresasEmpresaIdRoute: typeof AuthenticatedEmpresasEmpresaIdRoute
  AuthenticatedEmpresasIndexRoute: typeof AuthenticatedEmpresasIndexRoute
}

const AuthenticatedEmpresasRouteChildren: AuthenticatedEmpresasRouteChildren = {
  AuthenticatedEmpresasEmpresaIdRoute: AuthenticatedEmpresasEmpresaIdRoute,
  AuthenticatedEmpresasIndexRoute: AuthenticatedEmpresasIndexRoute,
}

const AuthenticatedEmpresasRouteWithChildren =
  AuthenticatedEmpresasRoute._addFileChildren(
    AuthenticatedEmpresasRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAtualizacoesRoute: typeof AuthenticatedAtualizacoesRoute
  AuthenticatedBaseLegalRoute: typeof AuthenticatedBaseLegalRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRouteWithChildren
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAtualizacoesRoute: AuthenticatedAtualizacoesRoute,
  AuthenticatedBaseLegalRoute: AuthenticatedBaseLegalRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRouteWithChildren,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
