/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSimuladorNcmRouteImport } from './routes/_authenticated/simulador-ncm'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as AuthenticatedSimplesDasRouteImport } from './routes/_authenticated/simples-das'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedMinhaEmpresaRouteImport } from './routes/_authenticated/minha-empresa'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedBaseLegalRouteImport } from './routes/_authenticated/base-legal'
import { Route as AuthenticatedBaixarAppRouteImport } from './routes/_authenticated/baixar-app'
import { Route as AuthenticatedAtualizacoesRouteImport } from './routes/_authenticated/atualizacoes'
import { Route as AuthenticatedAnaliseComparativaRouteImport } from './routes/_authenticated/analise-comparativa'
import { Route as AuthenticatedEmpresasIndexRouteImport } from './routes/_authenticated/empresas.index'
import { Route as AuthenticatedEmpresasEmpresaIdRouteImport } from './routes/_authenticated/empresas.$empresaId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimuladorNcmRoute =
  AuthenticatedSimuladorNcmRouteImport.update({
    id: '/simulador-ncm',
    path: '/simulador-ncm',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSimplesDasRoute = AuthenticatedSimplesDasRouteImport.update({
  id: '/simples-das',
  path: '/simples-das',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhaEmpresaRoute =
  AuthenticatedMinhaEmpresaRouteImport.update({
    id: '/minha-empresa',
    path: '/minha-empresa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBaseLegalRoute = AuthenticatedBaseLegalRouteImport.update({
  id: '/base-legal',
  path: '/base-legal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBaixarAppRoute = AuthenticatedBaixarAppRouteImport.update({
  id: '/baixar-app',
  path: '/baixar-app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtualizacoesRoute =
  AuthenticatedAtualizacoesRouteImport.update({
    id: '/atualizacoes',
    path: '/atualizacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnaliseComparativaRoute =
  AuthenticatedAnaliseComparativaRouteImport.update({
    id: '/analise-comparativa',
    path: '/analise-comparativa',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresasIndexRoute =
  AuthenticatedEmpresasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)
const AuthenticatedEmpresasEmpresaIdRoute =
  AuthenticatedEmpresasEmpresaIdRouteImport.update({
    id: '/$empresaId',
    path: '/$empresaId',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analise-comparativa': typeof AuthenticatedAnaliseComparativaRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/base-legal': typeof AuthenticatedBaseLegalRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/simples-das': typeof AuthenticatedSimplesDasRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/simulador-ncm': typeof AuthenticatedSimuladorNcmRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
  '/empresas/': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analise-comparativa': typeof AuthenticatedAnaliseComparativaRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/base-legal': typeof AuthenticatedBaseLegalRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/simples-das': typeof AuthenticatedSimplesDasRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/simulador-ncm': typeof AuthenticatedSimuladorNcmRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
  '/empresas': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/analise-comparativa': typeof AuthenticatedAnaliseComparativaRoute
  '/_authenticated/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/_authenticated/baixar-app': typeof AuthenticatedBaixarAppRoute
  '/_authenticated/base-legal': typeof AuthenticatedBaseLegalRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/_authenticated/minha-empresa': typeof AuthenticatedMinhaEmpresaRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/simples-das': typeof AuthenticatedSimplesDasRoute
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
  '/_authenticated/simulador-ncm': typeof AuthenticatedSimuladorNcmRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/empresas/$empresaId': typeof AuthenticatedEmpresasEmpresaIdRoute
  '/_authenticated/empresas/': typeof AuthenticatedEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analise-comparativa'
    | '/atualizacoes'
    | '/baixar-app'
    | '/base-legal'
    | '/checklist'
    | '/dashboard'
    | '/empresas'
    | '/minha-empresa'
    | '/precificacao'
    | '/simples-das'
    | '/simulador'
    | '/simulador-ncm'
    | '/usuarios'
    | '/empresas/$empresaId'
    | '/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analise-comparativa'
    | '/atualizacoes'
    | '/baixar-app'
    | '/base-legal'
    | '/checklist'
    | '/dashboard'
    | '/minha-empresa'
    | '/precificacao'
    | '/simples-das'
    | '/simulador'
    | '/simulador-ncm'
    | '/usuarios'
    | '/empresas/$empresaId'
    | '/empresas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analise-comparativa'
    | '/_authenticated/atualizacoes'
    | '/_authenticated/baixar-app'
    | '/_authenticated/base-legal'
    | '/_authenticated/checklist'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/minha-empresa'
    | '/_authenticated/precificacao'
    | '/_authenticated/simples-das'
    | '/_authenticated/simulador'
    | '/_authenticated/simulador-ncm'
    | '/_authenticated/usuarios'
    | '/_authenticated/empresas/$empresaId'
    | '/_authenticated/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulador-ncm': {
      id: '/_authenticated/simulador-ncm'
      path: '/simulador-ncm'
      fullPath: '/simulador-ncm'
      preLoaderRoute: typeof AuthenticatedSimuladorNcmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/simples-das': {
      id: '/_authenticated/simples-das'
      path: '/simples-das'
      fullPath: '/simples-das'
      preLoaderRoute: typeof AuthenticatedSimplesDasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-empresa': {
      id: '/_authenticated/minha-empresa'
      path: '/minha-empresa'
      fullPath: '/minha-empresa'
      preLoaderRoute: typeof AuthenticatedMinhaEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/base-legal': {
      id: '/_authenticated/base-legal'
      path: '/base-legal'
      fullPath: '/base-legal'
      preLoaderRoute: typeof AuthenticatedBaseLegalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/baixar-app': {
      id: '/_authenticated/baixar-app'
      path: '/baixar-app'
      fullPath: '/baixar-app'
      preLoaderRoute: typeof AuthenticatedBaixarAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/atualizacoes': {
      id: '/_authenticated/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AuthenticatedAtualizacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analise-comparativa': {
      id: '/_authenticated/analise-comparativa'
      path: '/analise-comparativa'
      fullPath: '/analise-comparativa'
      preLoaderRoute: typeof AuthenticatedAnaliseComparativaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas/': {
      id: '/_authenticated/empresas/'
      path: '/'
      fullPath: '/empresas/'
      preLoaderRoute: typeof AuthenticatedEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
    '/_authenticated/empresas/$empresaId': {
      id: '/_authenticated/empresas/$empresaId'
      path: '/$empresaId'
      fullPath: '/empresas/$empresaId'
      preLoaderRoute: typeof AuthenticatedEmpresasEmpresaIdRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
  }
}

interface AuthenticatedEmpresasRouteChildren {
  AuthenticatedEmpresasEmpresaIdRoute: typeof AuthenticatedEmpresasEmpresaIdRoute
  AuthenticatedEmpresasIndexRoute: typeof AuthenticatedEmpresasIndexRoute
}

const AuthenticatedEmpresasRouteChildren: AuthenticatedEmpresasRouteChildren = {
  AuthenticatedEmpresasEmpresaIdRoute: AuthenticatedEmpresasEmpresaIdRoute,
  AuthenticatedEmpresasIndexRoute: AuthenticatedEmpresasIndexRoute,
}

const AuthenticatedEmpresasRouteWithChildren =
  AuthenticatedEmpresasRoute._addFileChildren(
    AuthenticatedEmpresasRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnaliseComparativaRoute: typeof AuthenticatedAnaliseComparativaRoute
  AuthenticatedAtualizacoesRoute: typeof AuthenticatedAtualizacoesRoute
  AuthenticatedBaixarAppRoute: typeof AuthenticatedBaixarAppRoute
  AuthenticatedBaseLegalRoute: typeof AuthenticatedBaseLegalRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRouteWithChildren
  AuthenticatedMinhaEmpresaRoute: typeof AuthenticatedMinhaEmpresaRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedSimplesDasRoute: typeof AuthenticatedSimplesDasRoute
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
  AuthenticatedSimuladorNcmRoute: typeof AuthenticatedSimuladorNcmRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnaliseComparativaRoute: AuthenticatedAnaliseComparativaRoute,
  AuthenticatedAtualizacoesRoute: AuthenticatedAtualizacoesRoute,
  AuthenticatedBaixarAppRoute: AuthenticatedBaixarAppRoute,
  AuthenticatedBaseLegalRoute: AuthenticatedBaseLegalRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRouteWithChildren,
  AuthenticatedMinhaEmpresaRoute: AuthenticatedMinhaEmpresaRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedSimplesDasRoute: AuthenticatedSimplesDasRoute,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
  AuthenticatedSimuladorNcmRoute: AuthenticatedSimuladorNcmRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
